// src/routes/(auth)/onboarding/+page.svelte
<script lang="ts">
  import { goto } from "$app/navigation";
  import { Motion } from "svelte-motion";
  import {
    GraduationCap,
    Store,
    CheckCircle2,
    ChevronRight,
    ArrowRight,
    Search,
    QrCode,
    ShoppingBag,
    Leaf,
  } from "lucide-svelte";
  import { markOnboardingComplete } from "$lib/auth";

  type OnboardingStep = "college" | "role" | "discover" | "reserve" | "pickup";
  type UserRole = "student" | "partner";

  const COLLEGES = [
    { name: "UC Irvine", available: true },
    { name: "UCLA", available: false },
    { name: "UC Berkeley", available: false },
    { name: "UC San Diego", available: false },
    { name: "UC Davis", available: false },
    { name: "UC Santa Barbara", available: false },
    { name: "UC Santa Cruz", available: false },
    { name: "UC Riverside", available: false },
    { name: "UC Merced", available: false },
  ] as const;

  const steps: OnboardingStep[] = ["college", "role", "discover", "reserve", "pickup"];

  let step = $state<OnboardingStep>("college");
  let selectedCollege = $state("UC Irvine");
  let collegeSearch = $state("");
  let showCollegeDropdown = $state(false);
  let selectedRole = $state<UserRole | null>(null);

  const filteredColleges = $derived(
    COLLEGES.filter((college) => college.name.toLowerCase().includes(collegeSearch.toLowerCase()))
  );
  const stepIndex = $derived(steps.indexOf(step));
  const totalSteps = steps.length;

  function goNext() {
    const current = steps.indexOf(step);
    if (current < steps.length - 1) {
      step = steps[current + 1];
    }
  }

  function goBack() {
    const current = steps.indexOf(step);
    if (current > 0) {
      step = steps[current - 1];
    }
  }

  function handleSkip() {
    markOnboardingComplete();
    goto("/");
  }

  function handleComplete() {
    markOnboardingComplete();
    goto("/");
  }
</script>

<div class="min-h-screen flex flex-col" style="background-color: #F9F6F1">
  <div class="px-6 pt-14 pb-2">
    <div class="flex items-center gap-1.5">
      {#each Array.from({ length: totalSteps }) as _, i}
        <div class="flex-1 h-1 rounded-full overflow-hidden" style="background-color: #EDE8E1">
          <Motion
            let:motion
            initial={{ width: 0 }}
            animate={{ width: i <= stepIndex ? "100%" : "0%" }}
            transition={{ duration: 0.3 }}
          >
            <div use:motion class="h-full rounded-full" style="background-color: #006838"></div>
          </Motion>
        </div>
      {/each}
    </div>
    <div class="flex items-center justify-between mt-2">
      <span style="font-size: 0.68rem; color: #7A6B5A; font-weight: 600"
        >Step {stepIndex + 1} of {totalSteps}</span
      >
      {#if stepIndex > 0 && stepIndex < totalSteps - 1}
        <span class="flex items-center gap-0.5" style="font-size: 0.68rem; color: #7A6B5A">
          {#each Array.from({ length: stepIndex }) as _, i}
            <CheckCircle2 class="w-3 h-3" style="color: #006838" />
          {/each}
        </span>
      {/if}
    </div>
  </div>

  {#key step}
    <Motion
      let:motion
      initial={{ opacity: 0, x: 30 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -30 }}
      transition={{ duration: 0.28, ease: [0.32, 0.72, 0, 1] }}
    >
      <div use:motion class="flex-1 flex flex-col px-6 pb-10">
        {#if step === "college"}
          <div class="flex justify-center mt-6 mb-6">
            <svg
              width="56"
              height="56"
              viewBox="0 0 48 48"
              fill="none"
              aria-hidden="true"
              style="flex-shrink: 0; display: block"
            >
              <circle cx="24" cy="24" r="22" stroke="#8B6F47" stroke-width="1.8" fill="none" />
              <circle cx="24" cy="24" r="17" stroke="#8B6F47" stroke-width="1.5" fill="none" />
              <path
                d="M24 14 C27.5 18, 29.5 21.5, 29.5 25 C29.5 29, 27 32.5, 24 35 C21 32.5, 18.5 29, 18.5 25 C18.5 21.5, 20.5 18, 24 14Z"
                stroke="#8B6F47"
                stroke-width="1.8"
                fill="none"
                stroke-linejoin="round"
              />
              <line
                x1="24"
                y1="16"
                x2="24"
                y2="33.5"
                stroke="#8B6F47"
                stroke-width="1.5"
                stroke-linecap="round"
              />
            </svg>
          </div>

          <h1 style="font-size: 1.5rem; font-weight: 800; color: #1C2B1C; text-align: center">
            Welcome to EcoPlate
          </h1>
          <p class="text-center mt-2 mb-8" style="font-size: 0.875rem; color: #7A6B5A">
            Let's get you set up in 30 seconds
          </p>

          <label
            for="college-search"
            style="font-size: 0.78rem; font-weight: 700; color: #4A3728; margin-bottom: 8px; display: block"
          >
            Choose Your College
          </label>

          <div class="relative">
            <div
              class="flex items-center gap-2 px-4 py-3.5 rounded-2xl cursor-pointer"
              style="background-color: white; border: 2px solid rgba(0,104,56,0.2); box-shadow: 0 2px 8px rgba(0,0,0,0.04)"
            >
              <Search class="w-4 h-4 shrink-0" style="color: #8B6F47" />
              <input
                id="college-search"
                type="text"
                placeholder="Search colleges..."
                value={showCollegeDropdown ? collegeSearch : selectedCollege}
                oninput={(e) => {
                  collegeSearch = (e.currentTarget as HTMLInputElement).value;
                  showCollegeDropdown = true;
                }}
                onfocus={() => {
                  showCollegeDropdown = true;
                  collegeSearch = "";
                }}
                class="flex-1 bg-transparent outline-none"
                style="font-size: 0.9375rem; color: #1C2B1C"
              />
              <ChevronRight
                class="w-4 h-4 shrink-0 transition-transform"
                style={`color: #7A6B5A; transform: ${showCollegeDropdown ? "rotate(90deg)" : "rotate(0deg)"}`}
              />
            </div>

            {#if showCollegeDropdown}
              <Motion
                let:motion
                initial={{ opacity: 0, y: -8 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -8 }}
              >
                <div
                  use:motion
                  class="absolute top-full left-0 right-0 mt-1 rounded-xl overflow-hidden z-10 max-h-48 overflow-y-auto"
                  style="background-color: white; border: 1px solid rgba(0,104,56,0.12); box-shadow: 0 8px 24px rgba(0,0,0,0.1)"
                >
                  {#each filteredColleges as college}
                    <button
                      onclick={() => {
                        if (!college.available) return;
                        selectedCollege = college.name;
                        showCollegeDropdown = false;
                        collegeSearch = "";
                      }}
                      class="w-full text-left px-4 py-3 flex items-center justify-between transition-colors"
                      style={`background-color: ${selectedCollege === college.name ? "#E8F5EE" : "transparent"}; border-bottom: 1px solid #F8F5F0; opacity: ${college.available ? 1 : 0.45}; cursor: ${college.available ? "pointer" : "default"}`}
                    >
                      <span
                        style={`font-size: 0.85rem; color: ${college.available ? "#1C2B1C" : "#A09890"}; font-weight: ${selectedCollege === college.name ? 700 : 400}`}
                      >
                        {college.name}
                      </span>
                      {#if selectedCollege === college.name && college.available}
                        <CheckCircle2 class="w-4 h-4" style="color: #006838" />
                      {:else if !college.available}
                        <span style="font-size: 0.62rem; color: #B0A898; font-weight: 600"
                          >Coming soon</span
                        >
                      {/if}
                    </button>
                  {/each}
                </div>
              </Motion>
            {/if}
          </div>

          <div class="flex-1"></div>

          <button
            onclick={goNext}
            disabled={!selectedCollege}
            class="w-full py-4 rounded-2xl flex items-center justify-center gap-2 active:scale-[0.98] transition-transform"
            style={`background-color: ${selectedCollege ? "#006838" : "#C4B9A8"}; color: white; font-size: 1rem; font-weight: 700; box-shadow: ${selectedCollege ? "0 4px 16px rgba(0,104,56,0.3)" : "none"}; cursor: ${selectedCollege ? "pointer" : "not-allowed"}`}
          >
            Continue
            <ArrowRight class="w-4 h-4" />
          </button>

          <button
            onclick={handleSkip}
            class="w-full mt-3 py-2 text-center"
            style="font-size: 0.78rem; color: #B0A898">Skip for Demo</button
          >
        {:else if step === "role"}
          <h1
            class="mt-6 mb-2"
            style="font-size: 1.375rem; font-weight: 800; color: #1C2B1C; text-align: center"
          >
            Choose Your Role at {selectedCollege}
          </h1>
          <p class="text-center mb-8" style="font-size: 0.85rem; color: #7A6B5A">
            This helps us personalize your experience
          </p>

          <div class="space-y-3 mb-auto">
            <button
              onclick={() => (selectedRole = "student")}
              class="w-full rounded-2xl p-5 text-left transition-all active:scale-[0.99]"
              style={`background-color: ${selectedRole === "student" ? "#E8F5EE" : "white"}; border: 2px solid ${selectedRole === "student" ? "#006838" : "rgba(0,104,56,0.1)"}; box-shadow: ${selectedRole === "student" ? "0 4px 16px rgba(0,104,56,0.12)" : "0 1px 4px rgba(0,0,0,0.04)"}`}
            >
              <div class="flex items-start gap-4">
                <div
                  class="w-12 h-12 rounded-full flex items-center justify-center shrink-0"
                  style="background-color: #E8F5EE"
                >
                  <GraduationCap class="w-6 h-6" style="color: #006838" />
                </div>
                <div>
                  <p style="font-size: 1rem; font-weight: 700; color: #1C2B1C">I'm a Student</p>
                  <p style="font-size: 0.8rem; color: #7A6B5A; margin-top: 2px">
                    Find affordable rescued meals near you
                  </p>
                </div>
              </div>
            </button>

            <button
              onclick={() => (selectedRole = "partner")}
              class="w-full rounded-2xl p-5 text-left transition-all active:scale-[0.99]"
              style={`background-color: ${selectedRole === "partner" ? "#FEF3C7" : "white"}; border: 2px solid ${selectedRole === "partner" ? "#D97706" : "rgba(0,104,56,0.1)"}; box-shadow: ${selectedRole === "partner" ? "0 4px 16px rgba(217,119,6,0.12)" : "0 1px 4px rgba(0,0,0,0.04)"}`}
            >
              <div class="flex items-start gap-4">
                <div
                  class="w-12 h-12 rounded-full flex items-center justify-center shrink-0"
                  style="background-color: #FEF3C7"
                >
                  <Store class="w-6 h-6" style="color: #D97706" />
                </div>
                <div>
                  <p style="font-size: 1rem; font-weight: 700; color: #1C2B1C">
                    I'm a Dining Partner
                  </p>
                  <p style="font-size: 0.8rem; color: #7A6B5A; margin-top: 2px">
                    Post surplus food responsibly
                  </p>
                </div>
              </div>
            </button>
          </div>

          <div class="flex-1"></div>

          <button
            onclick={goNext}
            disabled={!selectedRole}
            class="w-full py-4 rounded-2xl flex items-center justify-center gap-2 active:scale-[0.98] transition-transform"
            style={`background-color: ${selectedRole ? "#006838" : "#C4B9A8"}; color: white; font-size: 1rem; font-weight: 700; box-shadow: ${selectedRole ? "0 4px 16px rgba(0,104,56,0.3)" : "none"}; cursor: ${selectedRole ? "pointer" : "not-allowed"}`}
          >
            Continue
            <ArrowRight class="w-4 h-4" />
          </button>

          <button
            onclick={goBack}
            class="w-full mt-3 py-2 text-center"
            style="font-size: 0.78rem; color: #8B6F47">Back to College Selection</button
          >
        {:else if step === "discover"}
          <div class="flex-1 flex flex-col items-center justify-center">
            <div
              class="w-24 h-24 rounded-full flex items-center justify-center mb-6"
              style="background-color: #E8F5EE"
            >
              <QrCode class="w-12 h-12" style="color: #006838" />
            </div>
            <h1 style="font-size: 1.5rem; font-weight: 800; color: #1C2B1C; text-align: center">
              Discover Rescue Boxes
            </h1>
            <p
              class="text-center mt-3 mb-2"
              style="font-size: 0.9rem; color: #7A6B5A; max-width: 280px"
            >
              Scan the QR code at any dining hall to see tonight's available Rescue Boxes.
            </p>
            <p class="text-center mb-auto" style="font-size: 0.78rem; color: #B0A898">
              No account required to browse
            </p>
          </div>

          <div class="flex-1"></div>

          <button
            onclick={goNext}
            class="w-full py-4 rounded-2xl flex items-center justify-center gap-2 active:scale-[0.98] transition-transform"
            style="background-color: #006838; color: white; font-size: 1rem; font-weight: 700; box-shadow: 0 4px 16px rgba(0,104,56,0.3)"
          >
            Continue
            <ArrowRight class="w-4 h-4" />
          </button>
        {:else if step === "reserve"}
          <div class="flex-1 flex flex-col items-center justify-center">
            <div
              class="w-24 h-24 rounded-full flex items-center justify-center mb-6"
              style="background-color: #E8F5EE"
            >
              <ShoppingBag class="w-12 h-12" style="color: #006838" />
            </div>
            <h1 style="font-size: 1.5rem; font-weight: 800; color: #1C2B1C; text-align: center">
              Reserve in Seconds
            </h1>
            <p
              class="text-center mt-3 mb-2"
              style="font-size: 0.9rem; color: #7A6B5A; max-width: 280px"
            >
              Pick a box, tap reserve, done. It takes less than 30 seconds.
            </p>
            <p class="text-center mb-auto" style="font-size: 0.78rem; color: #B0A898">
              Rescue Boxes from $3-5 each
            </p>
          </div>

          <div class="flex-1"></div>

          <button
            onclick={goNext}
            class="w-full py-4 rounded-2xl flex items-center justify-center gap-2 active:scale-[0.98] transition-transform"
            style="background-color: #006838; color: white; font-size: 1rem; font-weight: 700; box-shadow: 0 4px 16px rgba(0,104,56,0.3)"
          >
            Continue
            <ArrowRight class="w-4 h-4" />
          </button>
        {:else}
          <div class="flex-1 flex flex-col items-center justify-center">
            <div
              class="w-24 h-24 rounded-full flex items-center justify-center mb-6"
              style="background-color: #E8F5EE"
            >
              <Leaf class="w-12 h-12" style="color: #006838" />
            </div>
            <h1 style="font-size: 1.5rem; font-weight: 800; color: #1C2B1C; text-align: center">
              Pick Up and Make Impact
            </h1>
            <p
              class="text-center mt-3 mb-2"
              style="font-size: 0.9rem; color: #7A6B5A; max-width: 300px"
            >
              Collect within 90 minutes and reduce food waste and emissions.
            </p>
            <p class="text-center mb-auto" style="font-size: 0.78rem; color: #B0A898">
              Every box rescued makes a difference
            </p>
          </div>

          <div class="flex-1"></div>

          <button
            onclick={handleComplete}
            class="w-full py-4 rounded-2xl flex items-center justify-center gap-2 active:scale-[0.98] transition-transform"
            style="background-color: #006838; color: white; font-size: 1rem; font-weight: 700; box-shadow: 0 4px 16px rgba(0,104,56,0.3)"
          >
            Get Started
            <ArrowRight class="w-4 h-4" />
          </button>
        {/if}
      </div>
    </Motion>
  {/key}
</div>

// src/app/components/onboarding.tsx
import { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  GraduationCap,
  Store,
  CheckCircle2,
  ChevronRight,
  ArrowRight,
  Search,
  QrCode,
  ShoppingBag,
  Leaf,
} from "lucide-react";
import { EcoplateLogo, EcoplateLogo_Icon } from "./ecoplate-logo";

type OnboardingStep = "college" | "role" | "discover" | "reserve" | "pickup" | "plan";

interface OnboardingProps {
  onComplete: (plan: "none" | "basic" | "premium") => void;
  onSkip: () => void;
}

const COLLEGES = [
  "UC Irvine",
  "UCLA",
  "UC Berkeley",
  "UC San Diego",
  "UC Davis",
  "UC Santa Barbara",
  "UC Santa Cruz",
  "UC Riverside",
  "UC Merced",
];

const PLANS = [
  {
    id: "none" as const,
    name: "Guest",
    price: "Free",
    desc: "Browse only, pay per box at listed price",
    features: ["Browse available drops", "Pay $3\u20135 per box"],
  },
  {
    id: "basic" as const,
    name: "Rescue Member",
    price: "$15/mo",
    desc: "7 credits per month",
    features: ["7 Rescue Credits/month", "Impact tracking", "Reservation history"],
    popular: true,
  },
  {
    id: "premium" as const,
    name: "Rescue Premium",
    price: "$30/mo",
    desc: "15 credits + early access",
    features: ["15 Rescue Credits/month", "30-min early access", "Priority waitlist", "Everything in Member"],
  },
];

export function Onboarding({ onComplete, onSkip }: OnboardingProps) {
  const [step, setStep] = useState<OnboardingStep>("college");
  const [selectedCollege, setSelectedCollege] = useState("UC Irvine");
  const [collegeSearch, setCollegeSearch] = useState("");
  const [showCollegeDropdown, setShowCollegeDropdown] = useState(false);
  const [selectedRole, setSelectedRole] = useState<"student" | "partner" | null>(null);
  const [selectedPlan, setSelectedPlan] = useState<"none" | "basic" | "premium">("basic");

  const filteredColleges = COLLEGES.filter((c) =>
    c.toLowerCase().includes(collegeSearch.toLowerCase())
  );

  const stepIndex = ["college", "role", "discover", "reserve", "pickup", "plan"].indexOf(step);
  const totalSteps = 6;

  const goNext = () => {
    const steps: OnboardingStep[] = ["college", "role", "discover", "reserve", "pickup", "plan"];
    const current = steps.indexOf(step);
    if (current < steps.length - 1) {
      setStep(steps[current + 1]);
    }
  };

  const goBack = () => {
    const steps: OnboardingStep[] = ["college", "role", "discover", "reserve", "pickup", "plan"];
    const current = steps.indexOf(step);
    if (current > 0) {
      setStep(steps[current - 1]);
    }
  };

  return (
    <div className="min-h-screen flex flex-col" style={{ backgroundColor: "#F9F6F1" }}>
      {/* Progress bar */}
      <div className="px-6 pt-14 pb-2">
        <div className="flex items-center gap-1.5">
          {Array.from({ length: totalSteps }).map((_, i) => (
            <div key={i} className="flex-1 h-1 rounded-full overflow-hidden" style={{ backgroundColor: "#EDE8E1" }}>
              <motion.div
                className="h-full rounded-full"
                style={{ backgroundColor: i < stepIndex ? "#006838" : i === stepIndex ? "#006838" : "transparent" }}
                initial={{ width: 0 }}
                animate={{ width: i <= stepIndex ? "100%" : "0%" }}
                transition={{ duration: 0.3 }}
              />
            </div>
          ))}
        </div>
        <div className="flex items-center justify-between mt-2">
          <span style={{ fontSize: "0.68rem", color: "#7A6B5A", fontWeight: 600 }}>
            Step {stepIndex + 1} of {totalSteps}
          </span>
          {stepIndex > 0 && stepIndex < totalSteps - 1 && (
            <span
              className="flex items-center gap-0.5"
              style={{ fontSize: "0.68rem", color: "#7A6B5A" }}
            >
              {Array.from({ length: stepIndex }).map((_, i) => (
                <CheckCircle2 key={i} className="w-3 h-3" style={{ color: "#006838" }} />
              ))}
            </span>
          )}
        </div>
      </div>

      <AnimatePresence mode="wait">
        {/* ── STEP 1: CHOOSE COLLEGE ──────────────────────────────────────── */}
        {step === "college" && (
          <motion.div
            key="college"
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -30 }}
            transition={{ duration: 0.2 }}
            className="flex-1 flex flex-col px-6 pb-10"
          >
            <div className="flex justify-center mt-6 mb-6">
              <EcoplateLogo_Icon size={56} color="#8B6F47" />
            </div>

            <h1 style={{ fontSize: "1.5rem", fontWeight: 800, color: "#1C2B1C", textAlign: "center" }}>
              Welcome to EcoPlate
            </h1>
            <p className="text-center mt-2 mb-8" style={{ fontSize: "0.875rem", color: "#7A6B5A" }}>
              Let's get you set up in 30 seconds
            </p>

            <label style={{ fontSize: "0.78rem", fontWeight: 700, color: "#4A3728", marginBottom: 8, display: "block" }}>
              Choose Your College
            </label>

            <div className="relative">
              <div
                className="flex items-center gap-2 px-4 py-3.5 rounded-2xl cursor-pointer"
                style={{
                  backgroundColor: "white",
                  border: "2px solid rgba(0,104,56,0.2)",
                  boxShadow: "0 2px 8px rgba(0,0,0,0.04)",
                }}
                onClick={() => setShowCollegeDropdown(!showCollegeDropdown)}
              >
                <Search className="w-4 h-4 shrink-0" style={{ color: "#8B6F47" }} />
                <input
                  type="text"
                  placeholder="Search colleges..."
                  value={showCollegeDropdown ? collegeSearch : selectedCollege}
                  onChange={(e) => {
                    setCollegeSearch(e.target.value);
                    setShowCollegeDropdown(true);
                  }}
                  onFocus={() => {
                    setShowCollegeDropdown(true);
                    setCollegeSearch("");
                  }}
                  className="flex-1 bg-transparent outline-none"
                  style={{ fontSize: "0.9375rem", color: "#1C2B1C" }}
                />
                <ChevronRight
                  className="w-4 h-4 shrink-0 transition-transform"
                  style={{ color: "#7A6B5A", transform: showCollegeDropdown ? "rotate(90deg)" : "rotate(0)" }}
                />
              </div>

              <AnimatePresence>
                {showCollegeDropdown && (
                  <motion.div
                    initial={{ opacity: 0, y: -8 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -8 }}
                    className="absolute top-full left-0 right-0 mt-1 rounded-xl overflow-hidden z-10 max-h-48 overflow-y-auto"
                    style={{ backgroundColor: "white", border: "1px solid rgba(0,104,56,0.12)", boxShadow: "0 8px 24px rgba(0,0,0,0.1)" }}
                  >
                    {filteredColleges.map((c) => (
                      <button
                        key={c}
                        onClick={() => {
                          setSelectedCollege(c);
                          setShowCollegeDropdown(false);
                          setCollegeSearch("");
                        }}
                        className="w-full text-left px-4 py-3 flex items-center justify-between transition-colors"
                        style={{
                          backgroundColor: selectedCollege === c ? "#E8F5EE" : "transparent",
                          borderBottom: "1px solid #F8F5F0",
                        }}
                      >
                        <span style={{ fontSize: "0.85rem", color: "#1C2B1C", fontWeight: selectedCollege === c ? 700 : 400 }}>
                          {c}
                        </span>
                        {selectedCollege === c && (
                          <CheckCircle2 className="w-4 h-4" style={{ color: "#006838" }} />
                        )}
                      </button>
                    ))}
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            <div className="flex-1" />

            <button
              onClick={goNext}
              disabled={!selectedCollege}
              className="w-full py-4 rounded-2xl flex items-center justify-center gap-2 active:scale-[0.98] transition-transform"
              style={{
                backgroundColor: selectedCollege ? "#006838" : "#C4B9A8",
                color: "white",
                fontSize: "1rem",
                fontWeight: 700,
                boxShadow: selectedCollege ? "0 4px 16px rgba(0,104,56,0.3)" : "none",
                cursor: selectedCollege ? "pointer" : "not-allowed",
              }}
            >
              Continue
              <ArrowRight className="w-4 h-4" />
            </button>

            <button
              onClick={onSkip}
              className="w-full mt-3 py-2 text-center"
              style={{ fontSize: "0.78rem", color: "#B0A898" }}
            >
              Skip for Demo
            </button>
          </motion.div>
        )}

        {/* ── STEP 2: CHOOSE ROLE ─────────────────────────────────────────── */}
        {step === "role" && (
          <motion.div
            key="role"
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -30 }}
            transition={{ duration: 0.2 }}
            className="flex-1 flex flex-col px-6 pb-10"
          >
            <h1
              className="mt-6 mb-2"
              style={{ fontSize: "1.375rem", fontWeight: 800, color: "#1C2B1C", textAlign: "center" }}
            >
              Choose Your Role at {selectedCollege}
            </h1>
            <p className="text-center mb-8" style={{ fontSize: "0.85rem", color: "#7A6B5A" }}>
              This helps us personalize your experience
            </p>

            <div className="space-y-3 mb-auto">
              {/* Student card */}
              <button
                onClick={() => setSelectedRole("student")}
                className="w-full rounded-2xl p-5 text-left transition-all active:scale-[0.99]"
                style={{
                  backgroundColor: selectedRole === "student" ? "#E8F5EE" : "white",
                  border: `2px solid ${selectedRole === "student" ? "#006838" : "rgba(0,104,56,0.1)"}`,
                  boxShadow: selectedRole === "student" ? "0 4px 16px rgba(0,104,56,0.12)" : "0 1px 4px rgba(0,0,0,0.04)",
                }}
              >
                <div className="flex items-start gap-4">
                  <div
                    className="w-12 h-12 rounded-full flex items-center justify-center shrink-0"
                    style={{ backgroundColor: "#E8F5EE" }}
                  >
                    <GraduationCap className="w-6 h-6" style={{ color: "#006838" }} />
                  </div>
                  <div>
                    <p style={{ fontSize: "1rem", fontWeight: 700, color: "#1C2B1C" }}>
                      I'm a Student
                    </p>
                    <p style={{ fontSize: "0.8rem", color: "#7A6B5A", marginTop: 2 }}>
                      Find affordable rescued meals near you
                    </p>
                  </div>
                </div>
              </button>

              {/* Dining Partner card */}
              <button
                onClick={() => setSelectedRole("partner")}
                className="w-full rounded-2xl p-5 text-left transition-all active:scale-[0.99]"
                style={{
                  backgroundColor: selectedRole === "partner" ? "#FEF3C7" : "white",
                  border: `2px solid ${selectedRole === "partner" ? "#D97706" : "rgba(0,104,56,0.1)"}`,
                  boxShadow: selectedRole === "partner" ? "0 4px 16px rgba(217,119,6,0.12)" : "0 1px 4px rgba(0,0,0,0.04)",
                }}
              >
                <div className="flex items-start gap-4">
                  <div
                    className="w-12 h-12 rounded-full flex items-center justify-center shrink-0"
                    style={{ backgroundColor: "#FEF3C7" }}
                  >
                    <Store className="w-6 h-6" style={{ color: "#D97706" }} />
                  </div>
                  <div>
                    <p style={{ fontSize: "1rem", fontWeight: 700, color: "#1C2B1C" }}>
                      I'm a Dining Partner
                    </p>
                    <p style={{ fontSize: "0.8rem", color: "#7A6B5A", marginTop: 2 }}>
                      Post surplus food responsibly
                    </p>
                  </div>
                </div>
              </button>
            </div>

            <div className="flex-1" />

            <button
              onClick={goNext}
              disabled={!selectedRole}
              className="w-full py-4 rounded-2xl flex items-center justify-center gap-2 active:scale-[0.98] transition-transform"
              style={{
                backgroundColor: selectedRole ? "#006838" : "#C4B9A8",
                color: "white",
                fontSize: "1rem",
                fontWeight: 700,
                boxShadow: selectedRole ? "0 4px 16px rgba(0,104,56,0.3)" : "none",
                cursor: selectedRole ? "pointer" : "not-allowed",
              }}
            >
              Continue
              <ArrowRight className="w-4 h-4" />
            </button>

            <button
              onClick={goBack}
              className="w-full mt-3 py-2 text-center"
              style={{ fontSize: "0.78rem", color: "#8B6F47" }}
            >
              Back to College Selection
            </button>
          </motion.div>
        )}

        {/* ── STEP 3: DISCOVER ────────────────────────────────────────────── */}
        {step === "discover" && (
          <motion.div
            key="discover"
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -30 }}
            transition={{ duration: 0.2 }}
            className="flex-1 flex flex-col items-center justify-center px-6 pb-10"
          >
            <div
              className="w-24 h-24 rounded-full flex items-center justify-center mb-6"
              style={{ backgroundColor: "#E8F5EE" }}
            >
              <QrCode className="w-12 h-12" style={{ color: "#006838" }} />
            </div>
            <h1 style={{ fontSize: "1.5rem", fontWeight: 800, color: "#1C2B1C", textAlign: "center" }}>
              Discover Rescue Boxes
            </h1>
            <p className="text-center mt-3 mb-2" style={{ fontSize: "0.9rem", color: "#7A6B5A", maxWidth: 280 }}>
              Scan the QR code at any dining hall to see tonight's available Rescue Boxes.
            </p>
            <p className="text-center mb-auto" style={{ fontSize: "0.78rem", color: "#B0A898" }}>
              No account required to browse
            </p>

            <div className="flex-1" />

            <button
              onClick={goNext}
              className="w-full py-4 rounded-2xl flex items-center justify-center gap-2 active:scale-[0.98] transition-transform"
              style={{
                backgroundColor: "#006838",
                color: "white",
                fontSize: "1rem",
                fontWeight: 700,
                boxShadow: "0 4px 16px rgba(0,104,56,0.3)",
              }}
            >
              Continue
              <ArrowRight className="w-4 h-4" />
            </button>
          </motion.div>
        )}

        {/* ── STEP 4: RESERVE ─────────────────────────────────────────────── */}
        {step === "reserve" && (
          <motion.div
            key="reserve"
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -30 }}
            transition={{ duration: 0.2 }}
            className="flex-1 flex flex-col items-center justify-center px-6 pb-10"
          >
            <div
              className="w-24 h-24 rounded-full flex items-center justify-center mb-6"
              style={{ backgroundColor: "#E8F5EE" }}
            >
              <ShoppingBag className="w-12 h-12" style={{ color: "#006838" }} />
            </div>
            <h1 style={{ fontSize: "1.5rem", fontWeight: 800, color: "#1C2B1C", textAlign: "center" }}>
              Reserve in Seconds
            </h1>
            <p className="text-center mt-3 mb-2" style={{ fontSize: "0.9rem", color: "#7A6B5A", maxWidth: 280 }}>
              Pick a box, tap reserve, done. It takes less than 30 seconds.
            </p>
            <p className="text-center mb-auto" style={{ fontSize: "0.78rem", color: "#B0A898" }}>
              Rescue Boxes from $3&ndash;5 each
            </p>

            <div className="flex-1" />

            <button
              onClick={goNext}
              className="w-full py-4 rounded-2xl flex items-center justify-center gap-2 active:scale-[0.98] transition-transform"
              style={{
                backgroundColor: "#006838",
                color: "white",
                fontSize: "1rem",
                fontWeight: 700,
                boxShadow: "0 4px 16px rgba(0,104,56,0.3)",
              }}
            >
              Continue
              <ArrowRight className="w-4 h-4" />
            </button>
          </motion.div>
        )}

        {/* ── STEP 5: PICK UP ─────────────────────────────────────────────── */}
        {step === "pickup" && (
          <motion.div
            key="pickup"
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -30 }}
            transition={{ duration: 0.2 }}
            className="flex-1 flex flex-col items-center justify-center px-6 pb-10"
          >
            <div
              className="w-24 h-24 rounded-full flex items-center justify-center mb-6"
              style={{ backgroundColor: "#E8F5EE" }}
            >
              <Leaf className="w-12 h-12" style={{ color: "#006838" }} />
            </div>
            <h1 style={{ fontSize: "1.5rem", fontWeight: 800, color: "#1C2B1C", textAlign: "center" }}>
              Pick Up and Make Impact
            </h1>
            <p className="text-center mt-3 mb-2" style={{ fontSize: "0.9rem", color: "#7A6B5A", maxWidth: 300 }}>
              Collect within 90 minutes and reduce food waste and emissions.
            </p>
            <p className="text-center mb-auto" style={{ fontSize: "0.78rem", color: "#B0A898" }}>
              Every box rescued makes a difference
            </p>

            <div className="flex-1" />

            <button
              onClick={goNext}
              className="w-full py-4 rounded-2xl flex items-center justify-center gap-2 active:scale-[0.98] transition-transform"
              style={{
                backgroundColor: "#006838",
                color: "white",
                fontSize: "1rem",
                fontWeight: 700,
                boxShadow: "0 4px 16px rgba(0,104,56,0.3)",
              }}
            >
              Continue
              <ArrowRight className="w-4 h-4" />
            </button>
          </motion.div>
        )}

        {/* ── STEP 6: PLAN SELECTION ──────────────────────────────────────── */}
        {step === "plan" && (
          <motion.div
            key="plan"
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -30 }}
            transition={{ duration: 0.2 }}
            className="flex-1 flex flex-col px-6 pb-10"
          >
            <h1
              className="mt-4 mb-2"
              style={{ fontSize: "1.375rem", fontWeight: 800, color: "#1C2B1C", textAlign: "center" }}
            >
              Choose Your Plan
            </h1>
            <p className="text-center mb-6" style={{ fontSize: "0.85rem", color: "#7A6B5A" }}>
              Pick the option that fits your lifestyle
            </p>

            <div className="space-y-3 mb-4">
              {PLANS.map((plan) => {
                const isSelected = plan.id === selectedPlan;
                return (
                  <button
                    key={plan.id}
                    onClick={() => setSelectedPlan(plan.id)}
                    className="w-full text-left rounded-2xl p-4 transition-all active:scale-[0.99] relative"
                    style={{
                      backgroundColor: isSelected ? "#E8F5EE" : "white",
                      border: `2px solid ${isSelected ? "#006838" : "rgba(0,104,56,0.1)"}`,
                      boxShadow: isSelected ? "0 2px 12px rgba(0,104,56,0.1)" : "0 1px 4px rgba(0,0,0,0.04)",
                    }}
                  >
                    {plan.popular && (
                      <div
                        className="absolute -top-2.5 left-4 px-2.5 py-0.5 rounded-full"
                        style={{ backgroundColor: "#006838", color: "white", fontSize: "0.6rem", fontWeight: 700 }}
                      >
                        Most Popular
                      </div>
                    )}
                    <div className="flex items-start gap-3">
                      <div
                        className="w-5 h-5 rounded-full border-2 flex items-center justify-center mt-0.5 shrink-0"
                        style={{
                          borderColor: isSelected ? "#006838" : "#C4B9A8",
                          backgroundColor: isSelected ? "#006838" : "transparent",
                        }}
                      >
                        {isSelected && <div className="w-2 h-2 rounded-full bg-white" />}
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <p style={{ fontSize: "0.9rem", fontWeight: 700, color: "#1C2B1C" }}>
                            {plan.name}
                          </p>
                          <span style={{ fontSize: "0.9rem", fontWeight: 900, color: "#006838" }}>
                            {plan.price}
                          </span>
                        </div>
                        <p style={{ fontSize: "0.72rem", color: "#7A6B5A", marginTop: 2 }}>
                          {plan.desc}
                        </p>
                        <div className="mt-2 space-y-1">
                          {plan.features.map((f) => (
                            <div key={f} className="flex items-center gap-1.5">
                              <CheckCircle2 className="w-3 h-3 shrink-0" style={{ color: isSelected ? "#006838" : "#C4B9A8" }} />
                              <span style={{ fontSize: "0.7rem", color: "#7A6B5A" }}>{f}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </button>
                );
              })}
            </div>

            <div className="flex-1" />

            <button
              onClick={() => onComplete(selectedPlan)}
              className="w-full py-4 rounded-2xl flex items-center justify-center gap-2 active:scale-[0.98] transition-transform"
              style={{
                backgroundColor: "#006838",
                color: "white",
                fontSize: "1rem",
                fontWeight: 700,
                boxShadow: "0 4px 16px rgba(0,104,56,0.3)",
              }}
            >
              {selectedPlan === "none" ? "Start as Guest" : `Start ${PLANS.find(p => p.id === selectedPlan)?.name}`}
              <ArrowRight className="w-4 h-4" />
            </button>

            <button
              onClick={() => onComplete("none")}
              className="w-full mt-3 py-2 text-center"
              style={{ fontSize: "0.78rem", color: "#B0A898" }}
            >
              Skip for Now
            </button>
            <p className="text-center mt-2" style={{ fontSize: "0.68rem", color: "#C4BAB0" }}>
              You can always upgrade later from your profile
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
